/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primaryLight: "#00677c",
        primaryLightOn: "#ffffff",
        primaryLightContainer: "#b1ecff",
        primaryLightContainerOn: "#001f27",
        secondaryLight: "#0361a3",
        secondaryLightOn: "#ffffff",
        secondaryLightContainer: "#d6e8ce",
        secondaryLightContainerOn: "#001d36",
        tertiaryLight: "#1860a5",
        tertiaryLightOn: "#ffffff",
        tertiaryLightContainer: "#d3e3ff",
        tertiaryLightContainerOn: "#001c39",
        errorLight: "#ba1a1a",
        errorLightOn: "#ffffff",
        errorLightContainer: "#ffdad6",
        errorLightContainerOn: "#410002",
        backgroundLight: "#fdfcff",
        backgroundLightOn: "#001c3a",
        lightVariantSurface: "#fdfcff",
        lightVariantSurfaceOn: "#001c3a",
        lightOutline: "#70787c",

        primaryDark: "#58d6f7",
        primaryDarkOn: "#003641",
        primaryDarkContainer: "#004e5e",
        primaryDarkContainerOn: "#b1ecff",
        secondaryDark: "#9fcaff",
        secondaryDarkOn: "#003258",
        secondaryDarkContainer: "#00497d",
        secondaryDarkContainerOn: "#d1e4ff",
        tertiary: "#a3c9ff",
        tertiaryOn: "#00315c",
        tertiaryDarkContainer: "#004882",
        tertiaryDarkContainerOn: "#d3e3ff",
        errorDark: "#ffb4ab",
        errorDarkOn: "#690005",
        errorDarkContainer: "#93000a",
        errorDarkContainerOn: "#ffdad6",
        backgroundDark: "#001c3a",
        backgroundDarkOn: "#d4e3ff",
        darkSurface: "#001c3a",
        darkSurfaceOn: "#d4e3ff",
        darkVariantSurface: "#40484b",
        darkVariantSurfaceOn: "#bfc8cb",
        darkOutline: "#899296",
      },
    },
  },
  plugins: [],
};
